// <auto-generated />
namespace Vidzy_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FluentAPI4thIteration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FluentAPI4thIteration));
        
        string IMigrationMetadata.Id
        {
            get { return "202203012016593_FluentAPI4thIteration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
